preset: laravel

risky: false

linting: true

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow
  - single_blank_line_at_eof

disabled:
  - align_double_arrow
  - short_array_syntax
  - no_tab_indentation

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  contains:
    - "Foo"
  not-contains:
    - "config"
  path:
    - "foo/Stuff"
  not-path:
    - "libraries"
  depth:
    - "< 3"